/* eslint-disable react/no-unescaped-entities */
import Header from '@/components/header/header'
import './globals.css'
import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700',],
  variable: '--font-family',
})

export const metadata: Metadata = {
  title: 'Trivia Night',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body style={inter.style}>
        <Header />
        {children}
      </body>
    </html>
  )
}
