/* eslint-disable react/no-unescaped-entities */
import Header from '@/components/header/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'

const inter = Inter({
  subsets: ['latin'],
  // weight: ['400', '500', '600', '700',],
  variable: '--font-family',
})

export const metadata: Metadata = {
  title: 'Trivia Night',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
